apiVersion: v1
kind: Pod
metadata:
  generateName: first-pod-
spec:
 restartPolicy: OnFailure
 containers:
 - name: cudasample
   image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1
   args: ["-benchmark", "-numbodies=512000", "-fp64", "-fullscreen"]
   resources:
    requests:
     cpu: 2
     memory: "1Gi"
    limits:
     cpu: 4
     memory: "4Gi"
     nvidia.com/gpu: 1